### ISSUE TITLE
Error running conversion: 37 with open search results from MSFragger

### ISSUE THREAD

**Issue by fcyu** [yeastrc/limelight-import-philosopher-tsv#1]
Hi Mike,

I have an error with open search result. Following is the log:
```
java -jar C:\Users\yufe\Desktop\bin\philosopherTSV2LimelightXML.jar --open-mod -f=protein.fas -m=psm.tsv -o=psm.tsv.xml -p=fragger.params
MSFragger/TSV to limelight XML converter
Author: Michael Riffle <mriffle@uw.edu>
See: https://github.com/yeastrc/limelight-import-philosopher-tsv
Version: 1.0.1

Determining search program... Got: MSFragger
Reading conf file into memory... Done.
        Got static mods: {C=57.021460}
        Got decoy prefix: rev_
Reading search results (psm.tsv) into memory...Error running conversion: 37
```

I also put the files in the attachment.

Thanks,

Fengchao

[dev-limelight-open.zip](https://github.com/yeastrc/limelight-import-philosopher-tsv/files/6903297/dev-limelight-open.zip)

**Comment by mriffle** [comment]
Looks like when a peptide only matches a single protein the final two fields on that line are not present (final two fields being mapped genes and mapped proteins). Ideally these would be present but empty. I'll code up a workaround and post back here when I'm done.

**Comment by mriffle** [comment]
New release (1.0.2) up at https://github.com/yeastrc/limelight-import-philosopher-tsv/releases  Should gracefully handle this situation.

Thanks,
Mike

**Comment by fcyu** [comment]
Hi Mike,

Thanks for your prompt reply. The conversion finished without any errors. But when opening the peptide report in Limelight website, I get this error
![image](https://user-images.githubusercontent.com/6926299/127577934-902973cc-8ae5-4b3b-a74c-432d51947525.png)

Could you please provide any suggestions?

Thanks,

Fengchao

**Comment by mriffle** [comment]
Fengchao, 

Glad to hear re: converter. I think the error you're seeing is a bug we fixed recently in Limelight and we've put out a new version. To update your instance Limelight follow these instructions: https://limelight-ms.readthedocs.io/en/latest/administration/update-limelight.html

I just wrote that page, so if you spot any problems w/ the instructions, please let me know!

Mike

**Comment by fcyu** [comment]
Hi Mike,

It works like a charm! 

Thank you again for your prompt reply,

Fengchao
